# Generated by Django 3.1.6 on 2021-03-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='weapon',
            field=models.CharField(default='sword', max_length=60),
        ),
    ]
